language: python

python:
  - '2.7'

install:
  - pip install codecov pytest pytest-cov
  - pip install -r requirements.txt

script:
  - python -m unittest cobinhood.tests.test_cobinhood
  - pytest --cov=cobinhood
  - nosetests --with-coverage

after_success:
  - codecov
