language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest cobinhood.tests.test_cobinhood
  - coverage run cobinhood.tests.test_cobinhood.py

after_success:
  - codecov
