language: python

python:
  - '2.7'

install:
  - pip install codecov pytest
  - pip install -r requirements.txt

script:
  - python -m unittest cobinhood.tests.test_cobinhood
  - py.test cobinhood/cobinhood.py --cov=cobinhood

after_success:
  - codecov
